dist: trusty
group: edge
language: java
jdk: openjdk8
cache:
 directories:
 - $HOME/.m2
before_install:
 - cd sandwich-shop-manager
script:
 - mvn clean install
after_success:
 - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN